### ISSUE TITLE
[FEAT] Youtube Data API를 이용한 댄서의 Youtube Thumbnail, 제목 구현 

### ISSUE THREAD

**Issue by LeeSungNo-ian** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#94]
## 🎯 이슈 개요
| 이슈 내용 | Youtube Data API를 이용한 Thumbnail, 제목 구현 |
| --- | --- |
| 마감 일자 | 2022.07 |

## 🏹 Todo
 - [ ] Youtube Data API를 이용한 Thumbnail, 제목 구현
 - [ ] CollectionView 내부에 구현

**Comment by Apple-Kong** [comment]
이안! YoutubeAPI Key 노출 안되도록 gitignore 부탁드릴게요!!
