### ISSUE TITLE
[FEAT] Kingfisher 사용하여 이미지 불러오기

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#95]
## 🎯 이슈 개요
| 이슈 내용 | 이미지 불러올때 kingfisher 사용 |
| --- | --- |
| 마감 일자 | 2022.07 |

## 🏹 Todo
 - [x] Kingfisher 패키지 설치
 - [x] 사용법 숙지
 - [ ] 코드 수정

**Comment by Apple-Kong** [comment]
브랜치 새로 파서 작업 부탁드릴게요~!
